# Syntax: "Dropdown Option": "Actual GitHub Label Name"
"Aseko": "APP ASEKO"
"Homekit Controller": "APP HOMEKIT CONTROLLER"
"Rachio": "APP RACHIO"
"SmartThinQ": "APP SMARTTHINQ"
"TadoZones": "APP TADOZONES"
"Worx": "APP WORX"
