name: 🐛 Issue Report
description: File an issue report to help me improve
title: "[Issue]: "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue report!
  - type: dropdown
    id: label-dropdown
    attributes:
      label: What APP is this issue about?
      description: Select an option to automatically tag this issue.
      options:
        - Aseko
        - Homekit Controller
        - Rachio
        - SmartThinQ
        - TadoZones
        - Worx
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Issue description
      description: Tell us exactly what the issue is.
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low (Cosmetic issue)
        - Medium (Annoying but usable)
        - High (App crashes/blocks work)

